/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 mac-draco.glb --transform 
Files: mac-draco.glb [414.63KB] > C:\Users\LXT\Desktop\1_Projects\webpage\WebsiteLV\src\assets\mac-draco-transformed.glb [63.66KB] (85%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/mac-draco-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.keyboard.geometry} material={materials.PaletteMaterial002} position={[1.793, 0, 3.451]} />
      <group position={[0, -0.1, 3.394]}>
        <mesh geometry={nodes.Cube002.geometry} material={materials.PaletteMaterial003} />
        <mesh geometry={nodes.Cube002_1.geometry} material={materials.PaletteMaterial001} />
      </group>
      <mesh geometry={nodes.screen.geometry} material={materials['screen.001']} position={[0.002, 2.928, 0.327]} rotation={[1.585, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/mac-draco-transformed.glb')
